version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - "5432:5432"

  web:
    build: .
    tty: true
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/site-casamento
    ports:
      - "3000:3000"
    depends_on:
      - db