version: '3'
services:
  db:
    image: postgres
    container_name: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "pass"

  web:
    build: .
    tty: true
    container_name: web
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/site-casamento
    ports:
      - "3000:3000"
    links:
      - db
